server:
  port: ${PORT:0}
  
spring:
  application:
    name: treinamento-oauth

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url: 
      defaultZone: http://localhost:8761/eureka

feign:
  client:
    config:
      default: 
        connectTimeout: 16000
        readTimeout: 160000