server:
  port: 8080
  servlet: 
    context-path: /treinamento
  
spring:
  application:
    name: treinamento
  datasource:
    url: jdbc:postgresql://localhost:5432/
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345678
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
