server:
  port: 8765
  
spring:
  application:
    name: treinamento-zuul-server

eureka:
  client: 
    service-url: 
      defaultZone: http://localhost:8761/eureka

zuul:
  routes:
    worker:
      service-id: treinamento-usuario
      path: /treinamento-usuario/**
    payroll:
      service-id: treinamento
      path: /treinamento/**
    user:
      service-id: treinamento-login
      path: /treinamento-login/**
    oauth:
      service-id: treinamento-oauth
      path: /treinamento-oauth/**
      sensitive-headers: Cookie,Set-Cookie

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
            
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 20000
